language: emacs-lisp
env:
  matrix:
    - EVM_EMACS=emacs-24.3-bin
    - EVM_EMACS=emacs-24.4-bin
    - EVM_EMACS=emacs-24.5-bin
install:
  - sudo mkdir /usr/local/evm
  - sudo chown $(id -u):$(id -g) /usr/local/evm
  - curl -fsSkL --max-time 10 --retry 10 --retry-delay 10 https://raw.github.com/rejeep/evm/master/go | bash
  - export PATH="$HOME/.evm/bin:$PATH"
  - evm install $EVM_EMACS --use
  - curl -fsSkL --max-time 10 --retry 10 --retry-delay 10 https://raw.github.com/cask/cask/master/go | python
  - export PATH="$HOME/.cask/bin:$PATH"
  - cask
script:
  make test
notifications:
  slack:
    secure: YxJhJnJMVZzDruAqOigEvL10XRD/ghYdsIjzXX3InrrW3JgYKVxb1no/5TkRcM9B1oWctH5ZkRST9wdaMKo9gnRWVaJBhtxazg/QEKv+n7kTSMtrtGAO71KZ2jFuNhn22hryJCNJB5laWBCzNxNelWEgS0Q7+HnuRED1GTcairM=
